'use client'
import { db } from "@/firebaseConfig";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { collection, addDoc } from 'firebase/firestore'
import React, { useState } from "react";


async function addDataToFireStore(name, email, message) {
  try {
    const docRef = await addDoc(collection(db, "message"), {
      name: name,
      email: email,
      message: message
    });
    console.log("document written with ID: ", docRef.id)
    return true;
  } catch (error) {
    console.error("error adding doc", error)
    return false
  }
}

export default function Home() {
  const [name, setName] = useState("")
  const [email, setEmail] = useState("")
  const [message, setMessage] = useState("")

  const handleSubmit = async (e) => {
    e.preventDefault()
    const added = await addDataToFireStore(name, email, message);
    if (added) {
      setName("")
      setEmail("")
      setMessage("")

      alert("Data added to firestore db")
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>

        <h1>
          add data to firestore database
        </h1>
        <form onSubmit={handleSubmit}>
          <label htmlFor="name">Name:</label>
          <input type="text" id="name" value={name} onChange={(e) => setName(e.target.value)} />
          <label htmlFor="email">Email:</label>
          <input type="text" id="email" value={email} onChange={(e) => setEmail(e.target.value)} />
          <label htmlFor="message">Message:</label>
          <textarea rows={5} id="message" value={message} onChange={(e) => setMessage(e.target.value)}>
          </textarea>
          <button type='submit'>submit</button>
        </form>
      </main>
    </>
  );
}
